server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  instance:
    #    instance-id: order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

ribbon:
  #default timeout is 1s
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    # feign logger monitors which service at which level
    org.ilearn.springcloud.service.PaymentFeignService: debug