server:
  port: 3344

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FortuneWang95/config-repo.git
          search-paths:
            - cloud2023
          label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#expose an endpoint for bus refresh
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'